### ISSUE TITLE
running grunt gives error message: Local Npm module "grunt-log-headers" not found. Is it installed?

### ISSUE THREAD

**Issue by gtesslerge** [stevenvachon/grunt-log-headers#2]
I have it installed yet I get the erro rmessage

Local Npm module "grunt-log-headers" not found. Is it installed?

Any idea what is wrong?

**Comment by stevenvachon** [comment]
Are you using `require()` or `grunt.loadNpmTasks()`? What OS?

**Comment by stevenvachon** [comment]
```shell
$ node -e 'require("grunt").loadNpmTasks("grunt-log-headers")'
>> Local Npm module "grunt-log-headers" not found. Is it installed?
```

Please read the readme file.
