### ISSUE TITLE
grunt-log-headers not found is it instaled

### ISSUE THREAD

**Issue by gtesslerge** [stevenvachon/grunt-log-headers#3]
I still have the same issue.

windows 7

I read the readme and am using it EXACTLY as you wrote.  Please advise w/o closing the issue.

I have it installed yet I get the erro rmessage

Local Npm module "grunt-log-headers" not found. Is it installed?

Any idea what is wrong?

**Comment by stevenvachon** [comment]
That error message only appears when using `loadNpmTasks()`. If you were using `require()`, as the readme instructs, and it did happen to not find the module, the error would be very different: `Error: Cannot find module 'fake'`.
