### ISSUE TITLE
Continued grunt-log-headers not found is it installed

### ISSUE THREAD

**Issue by gtesslerge** [stevenvachon/grunt-log-headers#4]
I still have the same issue.

I am only referencing the glh in one place in my gruintfile.

snippet:

module.exports = function ( grunt ) {
	// Do grunt-related things in here
	require ( 'grunt-log-headers' ) ( grunt );	

	grunt.loadNpmTasks ( 'grunt-contrib-watch' );
	grunt.loadNpmTasks ( 'grunt-karma' );
	grunt.loadNpmTasks ( 'grunt-ngdocs' );
	grunt.loadNpmTasks ( 'grunt-contrib-connect' );
	grunt.loadNpmTasks ( 'grunt-contrib-copy' );
	grunt.loadNpmTasks ( 'grunt-contrib-clean' );
	grunt.loadNpmTasks ( 'grunt-mkdir' );
	grunt.loadNpmTasks ( 'grunt-jsdoc' );
	grunt.loadNpmTasks ( 'grunt-clear' );
	grunt.loadNpmTasks ( 'grunt-string-replace' );
	grunt.loadNpmTasks ( 'grunt-directory-to-html' );
	grunt.loadNpmTasks ( 'grunt-dom-munger' );
	grunt.loadNpmTasks ( 'grunt-text-replace' );
	grunt.loadNpmTasks ( 'grunt-contrib-less' );
	grunt.loadNpmTasks ( 'grunt-chmod' );
	grunt.loadNpmTasks ( 'grunt-docular' );
	grunt.loadNpmTasks ( 'grunt-run' );
	grunt.loadNpmTasks ( 'grunt-open' );
	grunt.loadNpmTasks ( 'grunt-wait' );
	grunt.loadNpmTasks ( 'grunt-prompt' );
	grunt.loadNpmTasks ( 'grunt-sort-json' );
	grunt.loadNpmTasks ( 'grunt-node-inspector' );

Advice please.

**Comment by stevenvachon** [comment]
Please stop creating new issues every time. You can comment on closed issues.

**Comment by stevenvachon** [comment]
What OS? What version of Node/io? Maybe create a repo for me to look at.

**Comment by clubdesign** [comment]
Having the same issue here.

MacOS, any node version (5.0).
module is present within the node_modules folder, then required in grunt file.

require('grunt-log-headers')(grunt);

Other noteable stuff running:
https://github.com/firstandthird/load-grunt-config
https://github.com/sindresorhus/time-grunt

Maybe there is a conflict between them?
Greets

**Comment by clubdesign** [comment]
Example Gruntfile:
`module.exports = function(grunt) {
	var config_file = "public/config/config.json";
	var path = require('path');
	var pkg = grunt.file.readJSON("package.json");
	var timestamp = grunt.template.today('yyyy-mm-dd-HH-MM-ss');

	if( !grunt.file.exists( config_file ) ) {
		grunt.file.copy( "public/config/defaults/config.json", "public/config/config.json" );
	}

	var custom_config = grunt.file.readJSON( config_file );
	
	var config = {
		pkg: pkg,
		current_version: pkg.version,
		cachebuster: new Date().getTime(),
		paths: {
		},
		timestamp: timestamp,
		custom: custom_config
	}

	require('time-grunt')(grunt);
	require('grunt-log-headers')(grunt);

	require('load-grunt-config')(grunt, {
		configPath: path.join(process.cwd(), 'grunt_tasks'),
		data: config
	});
};
`

**Comment by stevenvachon** [comment]
Because this library was a hack to begin with, I'm not really interested in fixing it. Maybe if you can convince me (?). I've honestly moved onto gulp and build scripts that don't even use task runners. PRs are, of course, welcome.

**Comment by clubdesign** [comment]
Nice story, but i am no interested in it. 
If you don`t support the library then write that into the readme or pull it down.

Thanks for your help.

**Comment by stevenvachon** [comment]
Lol, then don't ask for help, dumbass.

**Comment by clubdesign** [comment]
Don`t call me dumbass. The only dumbass here is you. Just check your friendly responses to everybody asking. If you aren`t able to be social, then don`t release Open Source Plugins. If you can`t handle the "stress" of 4 issues. LoL.

How can one be such a jerk.

**Comment by stevenvachon** [comment]
Perhaps it's the language barrier then -- you not being interested in my explanation sounded quite rude in English. I explained my "story" because I thought you deserved to know *why* I am not interested in fixing the issue. Plus, I'm not being paid for support.

**Comment by clubdesign** [comment]
No beeing paid is the sideeffect of open source projects. Anyway. Put "Plugin is not supported" into the readme and everything is fine for everyone.
